[package]
name = "rusty_scissors"
version = "1.3.0"
edition = "2021"
description = "A command-line tool for trimming images."
license = "MIT"

[dependencies]
image = "0.25.1"
walkdir = "2.5.0"
rayon = "1.10.0"
filetime = "0.2.23"